export const actionsTypes = {
    screen: 'SCR- SET',
    board: 'SET-BOARD',
    reload: 'RELOAD',
    selectMode: 'BTN-PRESS',
    totalMines: 'MINES',
    selectMine: 'MINE-ADD',
    unselectMine: 'MINE-REM',
    addFlag: 'FLAG-ADD',
    removeFlag: 'FLAG-REM',
    totalFields: 'FIELDS-SUM',
    revealField: 'FIELD-REV',
    power: 'SET-POWER',
    resolve: 'RESOLVE',
    start: 'START',
    end: 'END',
    editable: 'CONFIG-EDIT',
    backlight: 'CONFIG-LIGHT',
    sizeActive: 'CONFIG-SIZE',
    boardSize: 'GAMEPLAY-SIZE',
    mode: 'GAMEPLAY-MODE',
    style: 'GAMEPLAY-STYLE',
    detector: 'DETECT',
    setHidden: 'HIDDEN-CFG',
    addMine: 'HIDDEN-ADD',
    removeMine: 'HIDDEN-DEL',
    addField: 'HIDDEN-F-ADD',
    removeField: 'HIDDEN-F-DEL',
};